### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by Ashes47** [mrhan1993/Fooocus-API#82]
Can we please get a docker-compose file as well.

Thanks  a lot 😄

**Comment by mrhan1993** [comment]
@Ashes47 try this:
```yaml
version: "3.8"
services:
  fooocus-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fooocus-api
    volumes:
      - .:/app
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
